# Generated by Django 5.2 on 2025-09-14 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[\\d\\+\\-\\(\\)\\s]+$', 'Invalid contact format')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Only alphanumeric characters allowed')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only letters and spaces allowed')]),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_id',), name='unique_employee_id'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee_employee',
        ),
    ]
